Feature/preserve yaml comments
nitrictech/legacy-cli pull request #145
Opened 2021-08-16 05:34 UTC by jyecusch

Closes: https://github.com/nitrictech/cli/issues/99

2021-08-16 06:18 UTC, tjholm requested changes

2021-08-16 06:18 UTC, tjholm commented on packages/common/src/stack/stack.ts
>  	 * @param parser to parse the serialized file type, defaults to YAML parser.
remove @param parser

2021-08-16 06:18 UTC, tjholm commented on packages/common/src/stack/stack.ts
> +	}
can get rid of this if comments is defaulted to an empty array in the constructor and made non-optional as a field.

2021-08-16 06:18 UTC, tjholm commented on packages/common/src/stack/stack.ts
> +		const doc = insertComments(new YAML.Document(stack.asNitricStack(true)), stack.getComments());
as above, can access private comments if its non-optional.

2021-08-17 01:15 UTC, jyecusch commented on packages/common/src/stack/stack.ts
>  	 * @param parser to parse the serialized file type, defaults to YAML parser.
Done

2021-08-17 01:15 UTC, jyecusch commented on packages/common/src/stack/stack.ts
> +	}
Done

2021-08-17 01:15 UTC, jyecusch commented on packages/common/src/stack/stack.ts
> +		const doc = insertComments(new YAML.Document(stack.asNitricStack(true)), stack.getComments());
Done

2021-08-17 01:17 UTC, jyecusch commented
Resolved comments and added a basic test

2021-08-20 02:20 UTC, tjholm approved these changes

2021-08-26 05:50 UTC, merged