fix: fix issue with API spec generation for AWS API Gateway
nitrictech/legacy-cli pull request #170
Opened 2021-09-09 05:34 UTC by jyecusch

2021-09-09 06:30 UTC, tjholm requested changes

2021-09-09 06:30 UTC, tjholm commented on packages/plugins/aws/src/resources/api.ts
> +		const { name: nitricName } = api;
looks like nitricName is never used here.

2021-09-09 10:25 UTC, jyecusch commented on packages/plugins/aws/src/resources/api.ts
> +		const { name: nitricName } = api;
fixed, also accidentally left some debug code in too, removed that as well.

2021-09-12 22:29 UTC, tjholm approved these changes

2021-09-12 22:30 UTC, merged