WIP: Implement azure front door deployments.
nitrictech/legacy-cli pull request #178
Opened 2021-09-21 04:12 UTC by tjholm

2021-09-22 01:03 UTC, medgar-nitric approved these changes

2021-09-22 11:43 UTC, medgar-nitric approved these changes

2021-09-23 06:27 UTC, davemooreuws requested changes
Looks good to me, just two questions

2021-09-23 06:27 UTC, davemooreuws commented on packages/plugins/azure/src/resources/entrypoint.ts
> +					// FIXME: Add above defined pool name here...
Remove the FIXME? Looks like it was done.

2021-09-23 06:27 UTC, davemooreuws commented on packages/plugins/azure/src/resources/topic.ts
> +	// public getSharedAccessKeys = (): pulumi.Output<[string, string]> => {
Should this commented out code be removed?

2021-09-23 06:59 UTC, davemooreuws approved these changes

2021-09-23 07:01 UTC, merged