Feature/lock nitric version
nitrictech/legacy-cli pull request #195
Opened 2021-09-28 01:37 UTC by davemooreuws

closes #194

2021-09-30 04:14 UTC, tjholm approved these changes
LGTM

2021-09-30 05:24 UTC, jyecusch requested changes
Looks good, I've just suggested a few updates to the comments that could help with clarity

2021-09-30 05:24 UTC, jyecusch commented on packages/common/src/stack/function.ts
> +	 * @returns the stack version of the function, else the stack version
The comment seems a little confusing, isn't this returning the Membrane/framework version of the function? A slight update would be useful

2021-09-30 05:24 UTC, jyecusch commented on packages/common/src/stack/stack.ts
> +	 * @returns the stack version
A small update would add some clarity here, something like: 
`@returns the version of the nitric framework used by this stack`

2021-09-30 05:24 UTC, jyecusch commented on packages/common/src/types/stack.ts
> +	// Version of the Nitric Stack
I think this should be described as the Nitric Framework Version of the Stack

2021-10-05 04:16 UTC, jyecusch approved these changes

2021-10-05 04:16 UTC, merged