Feature/fix schedule
nitrictech/legacy-cli pull request #202
Opened 2021-10-07 17:35 UTC by raksiv

Schedule was not mapping to the right name property, and the topic was looking at ID not name.

2021-10-09 23:34 UTC, tjholm requested changes
Looks great! Should probably remove the manual changelog update (we should think about adding it to the ignore file).

2021-10-11 13:28 UTC, raksiv commented
Amended the commit to drop the changelog.

2021-10-11 21:51 UTC, tjholm approved these changes

2021-10-11 22:00 UTC, davemooreuws requested changes
Looks good to me, not sure about the changelog gitignore though

2021-10-11 22:00 UTC, davemooreuws commented on .gitignore
> +CHANGELOG.md
Shouldn't the change-log be pushed during release?

2021-10-12 17:42 UTC, raksiv commented on .gitignore
> +CHANGELOG.md
Not sure about this - happy to re-discuss
We currently agreed to keep it in gitignore.

2021-10-13 22:33 UTC, davemooreuws approved these changes

2021-10-13 22:33 UTC, merged