Fix/aws queues
nitrictech/legacy-cli pull request #203
Opened 2021-10-07 19:04 UTC by raksiv

Added queues constructor to the CLI with permissions for compute to work with queues.

2021-10-08 00:20 UTC, tjholm requested changes
Looks mostly good, just a quick comment on the commit history for this branch, as we're using conventional commits in our change logs could you squash/amend to add appropriate fix/feat tags for our changelogs

2021-10-08 01:08 UTC, jyecusch requested changes

2021-10-08 01:08 UTC, jyecusch commented on packages/plugins/aws/src/resources/queue.ts
> +		super('nitric:queue:StorageQueue', name, {}, opts);
Should be `super('nitric:queue:SQSQueue', ...`

2021-10-08 01:08 UTC, jyecusch commented on packages/plugins/aws/src/resources/queue.ts
> +				fifoQueue: false,
What are the default for these values, can we just omit them?

2021-10-08 01:08 UTC, jyecusch commented on packages/plugins/aws/src/resources/compute.ts
> +								'sqs:UntagQueue',
These permissions probably aren't needed:
- AddPermission
- CreateQueue
- DeleteQueue
- PurgeQueue
- RemovePermission
- SetQueueAttributes
- TagQueue
- UntagQueue

2021-10-08 01:24 UTC, jyecusch approved these changes

2021-10-09 23:32 UTC, tjholm approved these changes

2021-10-09 23:32 UTC, merged