GCP: Add queue deployments
nitrictech/legacy-cli pull request #212
Opened 2021-10-14 06:07 UTC by tjholm

2021-10-17 22:40 UTC, davemooreuws requested changes
Looks good, but I have a few comments around gcloud resource name validation and the topic reference. See review.

2021-10-17 22:40 UTC, davemooreuws commented on packages/plugins/gcp/src/resources/queue.ts
> +			topic: this.pubsub.id,
Is `this.pubsub.id` supposed to be `this.pubsub.name`? 
Ref: https://www.pulumi.com/docs/reference/pkg/gcp/pubsub/subscription/#pubsub-subscription-push

2021-10-17 22:40 UTC, davemooreuws commented on packages/plugins/gcp/src/resources/queue.ts
> +		new gcp.pubsub.Subscription(`${queue.name}-sub`, {
Not 100% sure about the resource name here. Might need to be changed for gcloud validation

References:
- https://cloud.google.com/pubsub/docs/admin#resource_names
- See merged PR for topic name https://github.com/nitrictech/cli/pull/215

2021-10-18 02:10 UTC, tjholm commented on packages/plugins/gcp/src/resources/queue.ts
> +			topic: this.pubsub.id,
result is the same in both cases, I suspect id === name.

Example using id:
![image](https://user-images.githubusercontent.com/13415171/137658594-601f8ebe-d083-4936-a996-116e0cbafc13.png)

can update to name to match docs though.

2021-10-18 02:14 UTC, tjholm commented on packages/plugins/gcp/src/resources/queue.ts
> +		new gcp.pubsub.Subscription(`${queue.name}-sub`, {
Subscriptions can only be created under a topic resource so I'm not sure the same change in the linked PR applies. (it needs to fully qualify the resource name within the project to properly target it as an unrelated resource).

Have you had issues with a gcp deployed project with these queue changes? As far as I can tell this is all working now.

2021-10-18 05:01 UTC, davemooreuws approved these changes

2021-10-19 03:13 UTC, medgar-nitric approved these changes

2021-10-19 21:58 UTC, merged