Container build refactor
nitrictech/legacy-cli pull request #223
Opened 2021-10-19 05:07 UTC by tjholm

2021-10-19 23:48 UTC, jyecusch requested changes
Looking good, just a couple of comments/questions.

2021-10-19 23:48 UTC, jyecusch commented on packages/common/src/task/build-container.ts
> +		// and delete it when we're done
Is this comment leftover from old code, I don't see an ignore file being created here.

2021-10-19 23:48 UTC, jyecusch commented on packages/common/src/task/build-container.ts
> +			});
Does the build output get displayed or logged anywhere (beside stderr)? Thinking about cases with large base images, for example, seeing download progress would be pretty useful. Could be a separate story to add good quality output without too much noise during the build.

2021-10-20 02:57 UTC, davemooreuws approved these changes

2021-10-20 09:27 UTC, tjholm commented on packages/common/src/task/build-container.ts
> +			});
Docker build using buildkit only outputs on stderr see: https://github.com/moby/buildkit/issues/1186.

Stdout is reserved for build artifact output.

It looks like there are options we can use to modify the buildkit progress output though. Will take a look at what we can do in a new issue.

2021-10-20 21:59 UTC, tjholm commented on packages/common/src/task/build-container.ts
> +		// and delete it when we're done
removed.

2021-10-20 22:00 UTC, tjholm commented on packages/common/src/task/build-container.ts
> +			});
Have put in --progress plain which cleans up the output somewhat, there is probably more we can do to make it cleaner though.

2021-10-26 01:04 UTC, jyecusch approved these changes

2021-10-26 01:04 UTC, merged