Fix failing AWS entrypoint deployments
nitrictech/legacy-cli pull request #72
Opened 2021-05-19 03:51 UTC by tjholm

2021-05-19 05:28 UTC, jyecusch requested changes

2021-05-19 05:28 UTC, jyecusch commented on packages/plugins/aws/src/tasks/deploy/entrypoint.ts
> +	pulumi.log.info("Begining deployment of API proxy", deployedService.awsLambda);
*beginning

2021-05-19 06:14 UTC, tjholm commented on packages/plugins/aws/src/tasks/deploy/entrypoint.ts
> +	pulumi.log.info("Begining deployment of API proxy", deployedService.awsLambda);
fixed

2021-05-20 01:19 UTC, jyecusch approved these changes

2021-05-20 01:19 UTC, merged